### ISSUE TITLE
Tabulator unable to be compiled by webpack

### ISSUE THREAD

**Issue by opolo** [surveyjs/survey-analytics#181]
Hi there!

Just wanted to report an error we encountered, while trying to test if we can use the analytics package in addition to the survey-js package as well :) It seems like the tabulator does not work, as we cannot import the CSS files for it. 

Our setup is a NextJS setup.* 

**Our package.json has these version-numbers:**
```
"@types/node": "^16.11.6",
"@types/react": "^17.0.34",
"babel-plugin-import": "^1.13.3",
"babel-plugin-styled-components": "1.13.3",
"next": "12.0.3",
"react": "17.0.2",
"survey-analytics": "1.8.76",
"survey-creator": "1.8.76",
"survey-react": "1.8.76",
"prettier": "2.4.1",
"typescript": "^4.4.4"
```

**The error we get is:**
```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
warn  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from C:\Projects\UI\AnalyticsFeasabilityTestProject\.babelrc
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
info  - Creating an optimized production build .(node:17680) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
info  - Creating an optimized production build
Failed to compile.

./node_modules/survey-analytics/survey.analytics.tabulator.css
TypeError: Cannot read property 'get' of undefined
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:63798:52
    at Hook.eval [as callAsync] (eval at create (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:9:1)
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:32883:43
    at symbolIterator (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\neo-async\async.js:1:14410)
    at timesSync (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\neo-async\async.js:1:5037)
    at Object.eachLimit (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\neo-async\async.js:1:14216)
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:32848:16
    at symbolIterator (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\neo-async\async.js:1:14452)
    at done (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\neo-async\async.js:1:14832)
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:32763:8
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:31273:32
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:47120:3
    at _done (eval at create (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:9:1)
    at Hook.eval [as callAsync] (eval at create (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:39:22)
    at Cache.store (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:23378:20)
    at ItemCacheFacade.store (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:23584:15)

Import trace for requested module:
./src/components/surveys/SurveyAnalyticsTabulatorComponent.tsx
./src/components/surveys/SurveyAnalyticsTabulatorComponentNoSsr.tsx
./src/components/pages/groups/tabs/surveys/SurveyAnalyticsTabulatorTab.tsx
./src/pages/groups/[groupId]/surveys/[surveyId]/analyze-tabulator-survey.tsx

data:image/svg+xml,<?xml version='1.0' encoding='utf-8'?><!./-- Generator: Adobe Illustrator 24.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0) --><svg version='1.1' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='htt
p://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 16 16' style='enable-background:new 0 0 16 16;' xml:space='preserve'><style type='text/css'> .st0{fill:rgba(159, 159, 159, 0.5);} .st1{fill:rgba(159, 159, 159, 0.5);}
</style><g><path class='st1' d='M8,2.03C3.63,2.03,0,8,0,8s3.63,6.03,8,6.03s8-6,8-6S12.37,2.03,8,2.03z M8,12c-2.58,0-5.13-2.81-6-4 c1.07-1.47,3.61-4,6-4c2.58,0,5.13,2.81,6,4C12.93,9.47,10.39,12,8,12z'/><circle class='st1' cx='8' cy='8'
r='3'/></g></svg>
Module build failed: UnhandledSchemeError: Reading from "data:image/svg+xml,<?xml version='1.0' encoding='utf-8'?><!./-- Generator: Adobe Illustrator 24.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0) --><svg version='1.1' id='Lay
er_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 16 16' style='enable-background:new 0 0 16 16;' xml:space='preserve'><style type='text/css'> .st0{fill:rgba(159, 159, 159,
 0.5);} .st1{fill:rgba(159, 159, 159, 0.5);}
</style><g><path class='st1' d='M8,2.03C3.63,2.03,0,8,0,8s3.63,6.03,8,6.03s8-6,8-6S12.37,2.03,8,2.03z M8,12c-2.58,0-5.13-2.81-6-4 c1.07-1.47,3.61-4,6-4c2.58,0,5.13,2.81,6,4C12.93,9.47,10.39,12,8,12z'/><circle class='st1' cx='8' cy='8'
r='3'/></g></svg>" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "data:" URIs.
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:54695:25
    at Hook.eval [as callAsync] (eval at create (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:16:1)
    at Object.processResource (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:54692:8)
    at processResource (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:139981:11)
    at iteratePitchingLoaders (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:139932:10)
    at runLoaders (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:140158:2)
    at NormalModule._doBuild (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:54682:3)
    at NormalModule.build (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:54826:15)
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:29346:12
    at NormalModule.needBuild (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:55113:32)
    at Compilation._buildModule (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:29327:10)
    at C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:122551:10
    at Hook.eval [as callAsync] (eval at create (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:141008:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:122541:26)
    at AsyncQueue._ensureProcessing (C:\Projects\UI\AnalyticsFeasabilityTestProject\node_modules\next\dist\compiled\webpack\bundle5.js:122528:12)
    at processImmediate (internal/timers.js:464:21)

Import trace for requested module:
./node_modules/survey-analytics/survey.analytics.tabulator.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpac
k/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./node_modules/survey-analytics/survey.analytics.tabulator.css
./node_modules/survey-analytics/survey.analytics.tabulator.css
./src/components/surveys/SurveyAnalyticsTabulatorComponent.tsx
./src/components/surveys/SurveyAnalyticsTabulatorComponentNoSsr.tsx
./src/components/pages/groups/tabs/surveys/SurveyAnalyticsTabulatorTab.tsx
./src/pages/groups/[groupId]/surveys/[surveyId]/analyze-tabulator-survey.tsx

> Build failed because of webpack errors

```
**Solution (not a working one)**
We can fix the error by removing the below line from the top of our Tabulator.tsx file (indicated with <-------):
```
import React, { useEffect, useMemo, useState } from 'react';
import * as Survey from 'survey-react';
import { Tabulator } from 'survey-analytics/survey.analytics.tabulator.js';

import 'survey-analytics/survey.analytics.tabulator.css'; <-------
import 'tabulator-tables/dist/css/tabulator.min.css';
```
 
However this also means that the styling on the component disappears, so it becomes a chaos without flexbox CSS applied to it, which renders it not usable in practice

**As an extra detail, a developer of ours managed to get the CSS to compile with Webpack if he used NextJS 11**
It uses an older webpack version. We believe the issue lies with the survey-analytics component's CSS not working with the newer Webpack versions. Unfortunately downgrading our NextJS server caused other issues with other components..

*NB. As a sidenote, this meant we also faced some other issues. this issues will likely be big entry barriers for other users as well - they were for us - which is why I mention these as well now :) Our solution could not be built with the Tabulator component referred for two other reason that we managed to fix: 
1. The analytics package did not work with SSR. We managed to fix this by wrapping the tabulator with: "export default dynamic(() => import('./SurveyAnalyticsTabulatorComponent'), { ssr: false });")
2. With the survey-analytics library referred, we could not built our nextJS solution due to some "can't resolve fs" error. We fixed this by adding: "config.resolve.fallback = { fs: false, path: false };" to our NextJS config.

**Comment by opolo** [comment]
Seems related to https://github.com/vercel/next.js/issues/31016
