### ISSUE TITLE
VisualizationPanel.getData throws the Uncaught TypeError: Cannot read properties of null (reading 'valueName') exception

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#350]
User issue:
T13500 - API to return data without Charts 
https://surveyjs.answerdesk.io/internal/ticket/details/T13500
***
Task: to get SurveyJS Dashboard data (an array of calculated and visualized values) from code without showing a Dashboard.

The [VisualizationPanel.getData](https://surveyjs.io/dashboard/documentation/api-reference/visualizationpanel#getData) function throws the following exception:
```
visualizerBase.ts:83 Uncaught TypeError: Cannot read properties of null (reading 'valueName')
    at VisualizationPanel.get (visualizerBase.ts:83:26)
    at ./src/dataProvider.ts.DataProvider.getStatisticsCacheKey (dataProvider.ts:27:32)
    at ./src/dataProvider.ts.DataProvider.getData (dataProvider.ts:188:27)
    at ./src/visualizerBase.ts.VisualizerBase.getData (visualizerBase.ts:468:30)
    at eval (eval at getData (App.js:1:1), <anonymous>:1:17)
    at getData (App.js:83:5)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:16)
    at invokeGuardedCallback (react-dom.development.js:4270:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4284:25)
    at executeDispatch (react-dom.development.js:9011:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9043:7)
    at processDispatchQueue (react-dom.development.js:9056:5)
    at dispatchEventsForPlugins (react-dom.development.js:9067:3)
    at eval (react-dom.development.js:9258:12)
    at batchedUpdates$1 (react-dom.development.js:25979:12)
    at batchedUpdates (react-dom.development.js:3984:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9257:3)
    at dispatchEvent (react-dom.development.js:6435:5)
    at dispatchDiscreteEvent (react-dom.development.js:6410:5)
get @ visualizerBase.ts:83
./src/dataProvider.ts.DataProvider.getStatisticsCacheKey @ dataProvider.ts:27
./src/dataProvider.ts.DataProvider.getData @ dataProvider.ts:188
./src/visualizerBase.ts.VisualizerBase.getData @ visualizerBase.ts:468
eval @ VM19851:1
getData @ App.js:83
callCallback @ react-dom.development.js:4157
invokeGuardedCallbackDev @ react-dom.development.js:4206
invokeGuardedCallback @ react-dom.development.js:4270
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4284
executeDispatch @ react-dom.development.js:9011
processDispatchQueueItemsInOrder @ react-dom.development.js:9043
processDispatchQueue @ react-dom.development.js:9056
dispatchEventsForPlugins @ react-dom.development.js:9067
eval @ react-dom.development.js:9258
batchedUpdates$1 @ react-dom.development.js:25979
batchedUpdates @ react-dom.development.js:3984
dispatchEventForPluginEventSystem @ react-dom.development.js:9257
dispatchEvent @ react-dom.development.js:6435
dispatchDiscreteEvent @ react-dom.development.js:6410
```

**Comment by JaneSjs** [comment]
It appears that the `getData` function should be called for a visualizer object instance (a chart) rather than the entire visualization panel. A visualizer object displays results of individual survey questions. 

If you create a Visualization Panel, you can obtain a specific question visualizer (a chart) using the [VisualizationPanel.getVisualizer](https://surveyjs.io/dashboard/documentation/api-reference/visualizationpanel#getVisualizer) function.
```js
const vizPanel = new VisualizationPanel(
      survey.getAllQuestions(),
      surveyResults,
      vizPanelOptions
);
    
let satisfactionScoreQuestionAnalyticsData = vizPanel.getVisualizer('satisfaction-score').getData();
//...
```
[View Demo](https://codesandbox.io/s/add-surveyjs-analytics-to-a-react-application-forked-w4z7lt?file=/src/App.js)

The 'satisfactionScoreQuestionAnalyticsData' object will contain an array of values calculated for a `satisfaction-score` chart.

Or, you may wish to programmatically create a visualizer for a specific survey question using the [VisualizerFactory.createVisualizer](https://surveyjs.io/dashboard/documentation/api-reference/visualizerfactory#createVisualizer) function. `VisualizerFactory` allows you to create individual visualizers without creating a [visualization panel](https://surveyjs.io/dashboard/documentation/api-reference/visualizationpanel).

Consider this example:
```js
import { VisualizerFactory } from "survey-analytics";

let satisfactionScoreQuestion = survey.getQuestionByName('satisfaction-score');

let satisfactionScoreChart = VisualizerFactory.createVisualizer(
      satisfactionScoreQuestion,
      surveyResults,
      { labelTruncateLength: 27 }
 );
let satisfactionScoreData = satisfactionScoreChart.getData();
//...
```
[View Demo](https://codesandbox.io/s/add-surveyjs-analytics-to-a-react-application-forked-ffzvx9?file=/src/App.js:2222-2447)
