### ISSUE TITLE
this.filteredData.forEach is not a function when loading an Image Picker question to a Dashboard

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-analytics#436]
[View Demo](https://plnkr.co/edit/LkxbZC6vzdxDo38f)

```
survey.analytics.min.js:23 Uncaught TypeError: this.filteredData.forEach is not a function
    at e.getDataCore (survey.analytics.min.js:23:66099)
    at e.getData (survey.analytics.min.js:23:66758)
    at e.getCalculatedValues (survey.analytics.min.js:23:75799)
    at t.getCalculatedValues (survey.analytics.min.js:23:129370)
    at t.getAnswersData (survey.analytics.min.js:23:90865)
    at e.setupBar (survey.analytics.min.js:23:122911)
    at e.setup (survey.analytics.min.js:23:121634)
    at e.create (survey.analytics.min.js:23:127138)
    at t.renderContent (survey.analytics.min.js:23:129224)
    at e.render (survey.analytics.min.js:23:73924)
```

**Comment by JaneSjs** [comment]
`data` should be an array. The updated demo: https://plnkr.co/edit/LkxbZC6vzdxDo38f
